### ISSUE TITLE
igor:  runtime: out of memory: cannot allocate xxxxxxxx-byte block (xxxxxxx in use)

### ISSUE THREAD

**Issue by YuntaoTan** [biogo/examples#10]
Hi, 
  biogo, developer.
I am using igor `igor -in hg_krishna.gff -out hg94_krishna.json` for grouping, my gff is 2.4G, but i got fllowing error, can you help me. 
```
runtime: out of memory: cannot allocate 597164032-byte block (3450306560 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x8165b5c, 0xd)
	/export/personal1/tanyt/software/go/src/runtime/panic.go:617 +0x6a
runtime.largeAlloc(0x23980000, 0x8090001, 0x673538f4)
	/export/personal1/tanyt/software/go/src/runtime/malloc.go:1057 +0x10f
runtime.mallocgc.func1()
	/export/personal1/tanyt/software/go/src/runtime/malloc.go:950 +0x39
runtime.systemstack(0x98840e0)
	/export/personal1/tanyt/software/go/src/runtime/asm_386.s:396 +0x53
```

**Comment by kortschak** [comment]
The out of memory throw is reporting that you are using 3.5GB, and that it's having a problem with allocating another 600MB. If this is the full system memory then I'm afraid you are out of luck; igor will not run with any reasonable genome in that amount of space. You need a bigger machine, or a machine that you can devote to igor during its run.

**Comment by YuntaoTan** [comment]
@kortschak , thanks for your quike response. 
    I am runing the igor on a large machine(3T memory), so  I don't think the resource may not be the reason. In another program `krishna` , I seen similar error info as following, so is that the golang has some problem when  deal with memory garbage collection, I guess may be. :
```
2019/08/13 11:25:04 problem with /export/personal1/tanyt/project/04huanghuali/01Repeat/NextRepeat/TEMask/RepeatMasker/split/LG04.fasta self: exit status 2
krishna:2019/08/13 11:22:04 [/export/personal1/tanyt/Pipeline/NextRepeat/pipeline3.3/software/CARP/bin/krishna -tmp=/tmp -threads=10 -log -filtid=0.94 -filtlen=400 -k 13 -target=/export/personal1/tanyt/project/
04huanghuali/01Repeat/NextRepeat/TEMask/RepeatMasker/split/LG04.fasta -self -out=LG04.gff]
krishna:2019/08/13 11:22:06 Reading /export/personal1/tanyt/project/04huanghuali/01Repeat/NextRepeat/TEMask/RepeatMasker/split/LG04.fasta: 535a4b889870bb59ed03ce710c8b441b
krishna:2019/08/13 11:22:07 Optimising filter parameters
krishna:2019/08/13 11:22:07 Using filter parameters:
krishna:2019/08/13 11:22:07     WordSize = 13
krishna:2019/08/13 11:22:07     MinMatch = 400
krishna:2019/08/13 11:22:07     MaxError = 24
krishna:2019/08/13 11:22:07     TubeOffset = 56
krishna:2019/08/13 11:22:07     Avg List Length = 1.290
krishna:2019/08/13 11:22:07 Using dynamic programming parameters:
krishna:2019/08/13 11:22:07     MinLen = 400
krishna:2019/08/13 11:22:07     MinID = 94.0%
krishna:2019/08/13 11:22:07 Estimated minimum memory required = 686MiB
krishna:2019/08/13 11:22:07 Building index for LG04.fasta
krishna:2019/08/13 11:22:07 Indexing
krishna:2019/08/13 11:22:26 Indexed
krishna:2019/08/13 11:22:26 Complementing query
krishna:2019/08/13 11:22:26 Filtering
krishna:2019/08/13 11:22:26 Complemented query
krishna:2019/08/13 11:22:26 Filtering
krishna:2019/08/13 11:24:58 Identified 7398095 filter hits
krishna:2019/08/13 11:24:58 Merging
krishna:2019/08/13 11:25:02 Identified 7432536 filter hits
krishna:2019/08/13 11:25:02 Merging
runtime: out of memory: cannot allocate 8192-byte block (2849406976 in use)
fatal error: out of memory

goroutine 143 [running]:
runtime.throw(0x83e8160, 0xd)
        /export/personal1/tanyt/software/go/src/runtime/panic.go:617 +0x6a fp=0xad1a63c sp=0xad1a628 pc=0x8072a9a
runtime.(*mcache).refill(0x55784368, 0x106)
        /export/personal1/tanyt/software/go/src/runtime/mcache.go:137 +0xec fp=0xad1a64c sp=0xad1a63c pc=0x805cbdc
runtime.(*mcache).nextFree(0x55784368, 0x6, 0x83b6a80, 0x2a12f9b0, 0x29cf35b0)
        /export/personal1/tanyt/software/go/src/runtime/malloc.go:786 +0x7a fp=0xad1a668 sp=0xad1a64c pc=0x8052fca
runtime.mallocgc(0x20, 0x83a1460, 0x5f5e101, 0x16)
        /export/personal1/tanyt/software/go/src/runtime/malloc.go:939 +0x5e7 fp=0xad1a6bc sp=0xad1a668 pc=0x8053757
runtime.newobject(0x83a1460, 0x2a12f9b0)
        /export/personal1/tanyt/software/go/src/runtime/malloc.go:1068 +0x2c fp=0xad1a6d0 sp=0xad1a6bc pc=0x8053a3c
github.com/biogo/biogo/align/pals/filter.(*Merger).MergeFilterHit(0xad76280, 0x2a12f9b0)
        /export/personal1/tanyt/Pipeline/NextRepeat/pipeline3.3/software/CARP/src/github.com/biogo/biogo/align/pals/filter/merge.go:124 +0x334 fp=0xad1a708 sp=0xad1a6d0 pc=0x8327104
github.com/biogo/biogo/align/pals.(*PALS).Align(0xa91e2a0, 0x8401c01, 0xa81e1f0, 0x0, 0x0, 0x0, 0x0)
        /export/personal1/tanyt/Pipeline/NextRepeat/pipeline3.3/software/CARP/src/github.com/biogo/biogo/align/pals/pals.go:303 +0x22e fp=0xad1a794 sp=0xad1a708 pc=0x8330cee
main.main.func3(0xa81e1f0, 0xa98e140, 0xa98ede0, 0xa98ede8, 0xa91e2a0, 0x1)
        /export/personal1/tanyt/Pipeline/NextRepeat/pipeline3.3/software/CARP/src/github.com/biogo/examples/krishna/krishna.go:249 +0x54 fp=0xad1a7d8 sp=0xad1a794 pc=0x8338424
runtime.goexit()
        /export/personal1/tanyt/software/go/src/runtime/asm_386.s:1321 +0x1 fp=0xad1a7dc sp=0xad1a7d8 pc=0x809c941
created by main.main
        /export/personal1/tanyt/Pipeline/NextRepeat/pipeline3.3/software/CARP/src/github.com/biogo/examples/krishna/krishna.go:247 +0x110b

goroutine 1 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0xa81e1f8)
        /export/personal1/tanyt/software/go/src/runtime/sema.go:56 +0x2e
sync.(*WaitGroup).Wait(0xa81e1f0)
        /export/personal1/tanyt/software/go/src/sync/waitgroup.go:130 +0x7d
main.main()
        /export/personal1/tanyt/Pipeline/NextRepeat/pipeline3.3/software/CARP/src/github.com/biogo/examples/krishna/krishna.go:296 +0x1127

```

**Comment by kortschak** [comment]
You are right, resources should not be an issue there, however the throw is not reporting memory use in the TB range, it is in the GB range. The krishna failure is failing to allocate a couple of pages beyond 2.8GB. Do you have any quotas or other limits in place?

Go has no problem with arenas in this size range since a long time ago. What version of Go did you build igor and krishna with?

**Comment by YuntaoTan** [comment]
I build tthe igor and krishna with go1.12.7.   fllowing is my machine memory: 
```
free -g -h 
              total        used        free      shared  buff/cache   available
Mem:           3.0T        1.1T        175G         66M        1.7T        1.8T
Swap:           31G         31M         31G

```
my machine  is a cloud server, is that my machine is not  compatible with  the golang?  It may be involved with my machine's  architecture.

**Comment by kortschak** [comment]
Are you able to log memory use during a run?

Out of interest, how many lines do you have in the GFF input to igor?

**Comment by YuntaoTan** [comment]
I have 27,882,527 lines in my gff. 
here is  my memory plot. but it only record the `igor`, not include the subprocess.

![mem_plot](https://user-images.githubusercontent.com/9817389/62925910-f3fb3d80-bde5-11e9-9443-0222d9b5fad4.png)

**Comment by kortschak** [comment]
Yeah, so that shows that we're falling over at 3GB. Even historically, the smallest arena size for the heap was 16GB. There's something going on outside what igor is doing on your hardware.

27M lines is not a lot. When I run human with default parameters, I get 140M lines and that runs with igor within ~100GB.

Can you post the complete stack trace for the igor crash.

**Comment by YuntaoTan** [comment]
fllowing is my cmd. `memory.sh` will stat the memory and plot.
```
export PATH=/export/personal1/tanyt/Pipeline/NextRepeat/pipeline3.3/software/CARP/bin:$PATH
memory.sh igor -in /export/personal1/tanyt/Pipeline/NextRepeat/pipeline3.3/software/CARP/mytest/big_test/hg_krishna.gff  -out /export/personal1/tanyt/Pipeline/NextRepeat/pipeline3.3/software/CARP/mytest/big_test/hg94_krishna.all.json
```
### here is my gff size:

$ ll  /export/personal1/tanyt/Pipeline/NextRepeat/pipeline3.3/software/CARP/mytest/big_test/hg_krishna.gff 
-rw-r--r-- 1 tanyt BGenome 2478016347 Aug 13 10:12 /export/personal1/tanyt/Pipeline/NextRepeat/pipeline3.3/software/CARP/mytest/big_test/hg_krishna.gff
```
```
### Here is my whole log file , when i run igor.
```
2019/08/13 16:11:06 reading PALS features from "/export/personal1/tanyt/Pipeline/NextRepeat/pipeline3.3/software/CARP/mytest/big_test/hg_krishna.gff"
2019/08/13 16:11:06 writing to "/export/personal1/tanyt/Pipeline/NextRepeat/pipeline3.3/software/CARP/mytest/big_test/hg94_krishna.all.json"
2019/08/13 16:11:06 generating piles ... piling.
runtime: out of memory: cannot allocate 597164032-byte block (3395649536 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x8165b5c, 0xd)
	/export/personal1/tanyt/software/go/src/runtime/panic.go:617 +0x6a
runtime.largeAlloc(0x23980000, 0x8090001, 0xa42f81b0)
	/export/personal1/tanyt/software/go/src/runtime/malloc.go:1057 +0x10f
runtime.mallocgc.func1()
	/export/personal1/tanyt/software/go/src/runtime/malloc.go:950 +0x39
runtime.systemstack(0x2be7a0e0)
	/export/personal1/tanyt/software/go/src/runtime/asm_386.s:396 +0x53
runtime.mstart()
	/export/personal1/tanyt/software/go/src/runtime/proc.go:1153

goroutine 1 [running]:
runtime.systemstack_switch()
	/export/personal1/tanyt/software/go/src/runtime/asm_386.s:357 fp=0x9510b84 sp=0x9510b80 pc=0x8091cd0
runtime.mallocgc(0x23980000, 0x814d180, 0x34c08a01, 0x989401d4)
	/export/personal1/tanyt/software/go/src/runtime/malloc.go:949 +0x67f fp=0x9510bd8 sp=0x9510b84 pc=0x8051baf
runtime.newarray(0x814d180, 0x220000, 0x8)
	/export/personal1/tanyt/software/go/src/runtime/malloc.go:1085 +0x44 fp=0x9510bec sp=0x9510bd8 pc=0x8051e94
runtime.makeBucketArray(0x81429c0, 0x15, 0x0, 0x8117386, 0x9510d5c)
	/export/personal1/tanyt/software/go/src/runtime/map.go:364 +0x146 fp=0x9510c04 sp=0x9510bec pc=0x8052be6
runtime.hashGrow(0x81429c0, 0x94eb2e0)
	/export/personal1/tanyt/software/go/src/runtime/map.go:1035 +0x74 fp=0x9510c28 sp=0x9510c04 pc=0x8054394
runtime.mapassign(0x81429c0, 0x94eb2e0, 0x9510d4c, 0x826a460)
	/export/personal1/tanyt/software/go/src/runtime/map.go:654 +0x141 fp=0x9510c78 sp=0x9510c28 pc=0x8053401
github.com/biogo/biogo/align/pals.(*Piler).Add(0x9510de4, 0x9b871d60, 0x34c08ac8, 0x9)
	/export/personal1/tanyt/Pipeline/NextRepeat/pipeline3.3/software/CARP/src/github.com/biogo/biogo/align/pals/piler.go:86 +0x3bb fp=0x9510d70 sp=0x9510c78 pc=0x811606b
github.com/biogo/examples/igor/igor.Piles(0x94ec140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3, 0x950ecfc, 0x94dde00)
	/export/personal1/tanyt/Pipeline/NextRepeat/pipeline3.3/software/CARP/src/github.com/biogo/examples/igor/igor/pile.go:51 +0x1df fp=0x9510e90 sp=0x9510d70 pc=0x812031f
main.main()
	/export/personal1/tanyt/Pipeline/NextRepeat/pipeline3.3/software/CARP/src/github.com/biogo/examples/igor/igor.go:163 +0x2c8 fp=0x9510fd0 sp=0x9510e90 pc=0x8123c58
runtime.main()
	/export/personal1/tanyt/software/go/src/runtime/proc.go:200 +0x1f3 fp=0x9510ff0 sp=0x9510fd0 pc=0x806fe03
runtime.goexit()
	/export/personal1/tanyt/software/go/src/runtime/asm_386.s:1321 +0x1 fp=0x9510ff4 sp=0x9510ff0 pc=0x8093511
Peak: 3313108
Loading required package: ggplot2

```

**Comment by YuntaoTan** [comment]
@kortschak    , thanks for your help.
but I have tried on another machine, the same error I got ;
```
2019/08/13 17:06:20 reading PALS features from "hg_krishna.gff"
2019/08/13 17:06:20 writing to "hg_krishna.json"
2019/08/13 17:06:20 generating piles ... piling.
runtime: out of memory: cannot allocate 597164032-byte block (3379036160 in use)
fatal error: out of memory
```
which version did you use?   I use the `go1.12.7.linux-386.tar.gz` , it is a binary version.  I want to have a try with your version.
Thank you.

**Comment by kortschak** [comment]
That last post answered the question. `go1.12.7.linux-386.tar.gz` is a 386 compiler, and so the arena size is limited to 32 bits. You want the amd64 compiler.

**Comment by YuntaoTan** [comment]
ohhh my god. I must have a try as soon.
Thank you very much. I seen the light.

**Comment by kortschak** [comment]
Yeah. This is why pasting the output of `go env` in bugs is useful.

**Comment by YuntaoTan** [comment]
Yes, that good.  you have rich experience. 
I am tring amd64, looks good.   this time it hava occupied 14Gb memory.
